[build]
  # Removed Python build command because the HTML and images are already statically generated.
  # This makes deployments instant.
  command = ""
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
